clear all;
close all;
clc;

addpath('../');
addpath('../external/');

options.hgtables = '../config/hgTables_b37.txt'; % human genome annotation table
options.gcdir = '/data/cyau/software/gc/b37/'; % directory of local GC content files
options.outdir = '/data/cyau/temp/'; % output directory
options.tumourStateTable = '../config/tumourStatesCLL.txt';

options.seqtype = 'cg'; % sequencing type 'cg' or 'illumina'
options.samplename = 'ps1-t1'; % sample name
options.infile = '/data/cyau/Enric/output/oncosnpseq_input/masterVarBeta-PS1_GS000017809-ASM-N1-T1-T2.T1'; % input data file

%dbstop if error

tic
oncoseq( 	'--diagnostics', ...
			'--read_depth_range', '[10:25]', ...
			'--chr_range', '[1:22]', ...
			'--n_train', '30000', ...
			'--maxploidy', '4.5', ...
			'--minploidy', '1.5', ...
			'--seqerror', '0.01', ...
			'--readerror', '0.01', ...
			'--fast', ...
			'--training', ...
			'--tumorheterogeneity', ...
			'--lambda1', '[1000 500 200 50 30]', ...
			'--tumourstatestable', options.tumourStateTable, ...
			'--hgtable', options.hgtables, ...
			'--gcdir', options.gcdir, ...
			'--seqtype', 'cg', ...
			'--samplename', options.samplename, ...
			'--infile', options.infile, ...
			'--outdir', options.outdir ...
		);
toc

%			'--training', ...
%			'--tumourheterogeneity', ...

