clear all;
close all;
clc;

addpath('../');
addpath('../external/');

options.hgtables = '../config/hgTables_b37.txt'; % human genome annotation table
options.gcdir = '/data/cyau/software/gc/b37/'; % directory of local GC content files
options.outdir = '/data/cyau/temp/'; % output directory
options.tumourStateTable = '../config/tumourStates.txt';

options.seqtype = 'cg'; % sequencing type 'cg' or 'illumina'
options.samplename = 'ps4-t2'; % sample name
options.infile = '/data/cyau/Enric/output/oncosnpseq_input/masterVarBeta-PS4_GS000017809-ASM-N1-T1-T2.T2'; % input data file

dbstop if error

tic
oncoseq( 	'--maxCopy', '10', ...
			'--diagnostics', ...
			'--read_depth_range', '[18]', ...
			'--chr_range', '[1:22]', ...
			'--n_train', '30000', ...
			'--maxploidy', '4.5', ...
			'--minploidy', '1.5', ...
			'--seqerror', '0.05', ...
			'--readerror', '0.05', ...
			'--normalcontamination', ...
			'--maxnormalcontamination', '0.5', ...
			'--tumourstatestable', options.tumourStateTable, ...
			'--hgtable', options.hgtables, ...
			'--gcdir', options.gcdir, ...
			'--seqtype', 'cg', ...
			'--samplename', options.samplename, ...
			'--infile', options.infile, ...
			'--outdir', options.outdir ...
		);
toc

