clear all;
close all;
clc;

addpath('../');
addpath('../external/');

rand('state', 1);
randn('state', 1);

options.hgtables = '../config/hgTables_b37.txt'; % human genome annotation table
options.gcdir = '/data/cyau/software/gc/b37/'; % directory of local GC content files
options.outdir = '/data/cyau/temp/'; % output directory
options.tumourStateTable = '../config/tumourStatesCLL.txt';


%options.seqtype = 'cg'; % sequencing type 'cg' or 'illumina'
%options.samplename = 'normal'; % sample name
%options.infile = '/home/cyau/projects/ahmed/scripts/normal.oncoseq'; % input data file


%dbstop if error


%tic
%oncoseq( 	'--read_depth_range', '[20:60]', ...
%			'--chr_range', '[1:22]', ...
%			'--n_train', '30000', ...
%			'--maxploidy', '3.5', ...
%			'--minploidy', '1.5', ...
%			'--seqerror', '0.05', ...
%			'--readerror', '0.05', ...
%			'--tumourstatestable', options.tumourStateTable, ...
%			'--hgtable', options.hgtables, ...
%			'--gcdir', options.gcdir, ...
%			'--seqtype', 'cg', ...
%			'--samplename', options.samplename, ...
%			'--infile', options.infile, ...
%			'--outdir', options.outdir ...
%		);
%toc

%break

options.seqtype = 'cg'; % sequencing type 'cg' or 'illumina'
options.samplename = 'lfr'; % sample name
options.infile = '/home/cyau/projects/ahmed/scripts/consensus.oncoseq'; % input data file


dbstop if error


tic
oncoseq( 	'--read_depth_range', '[5:20]', ...
			'--chr_range', '[1:22]', ...
			'--n_train', '30000', ...
			'--maxploidy', '3.5', ...
			'--minploidy', '1.5', ...
			'--seqerror', '0.01', ...
			'--readerror', '0.01', ...
			'--tumorheterogeneity', ...
			'--tumourstatestable', options.tumourStateTable, ...
			'--hgtable', options.hgtables, ...
			'--gcdir', options.gcdir, ...
			'--seqtype', 'cg', ...
			'--samplename', options.samplename, ...
			'--infile', options.infile, ...
			'--outdir', options.outdir ...
		);
toc

%%break;


