clear all;
close all;
clc;

addpath('../');
addpath('../external/');

rand('state', 1);
randn('state', 1);

options.hgtables = '../config/hgTables_b37.txt'; % human genome annotation table
options.gcdir = '/data/cyau/software/gc/b37/'; % directory of local GC content files
options.outdir = '/data/cyau/ahmed/oncoseq/output/'; % output directory
options.tumourStateTable = '../config/tumourStatesCLL.txt';

options.seqtype = 'cg'; % sequencing type 'cg' or 'illumina'



options.samplename = 'postchemo'; % sample name
options.infile = '/data/cyau/ahmed/oncoseq/postchemo.oncoseq'; % input data file

tic
oncoseq( 	'--read_depth_range', '[5:20]', ...
			'--chr_range', '[1:22]', ...
			'--n_train', '30000', ...
			'--maxploidy', '3.5', ...
			'--minploidy', '1.5', ...
			'--seqerror', '0.01', ...
			'--readerror', '0.1', ...
			'--normalcontamination', ...
			'--tumourstatestable', options.tumourStateTable, ...
			'--hgtable', options.hgtables, ...
			'--gcdir', options.gcdir, ...
			'--seqtype', 'cg', ...
			'--samplename', options.samplename, ...
			'--infile', options.infile, ...
			'--outdir', options.outdir ...
		);
toc




options.samplename = 'prechemo-all'; % sample name
options.infile = '/data/cyau/ahmed/oncoseq/prechemo-all.oncoseq'; % input data file

tic
oncoseq( 	'--read_depth_range', '[5:20]', ...
			'--chr_range', '[1:22]', ...
			'--n_train', '30000', ...
			'--maxploidy', '3.5', ...
			'--minploidy', '1.5', ...
			'--seqerror', '0.01', ...
			'--readerror', '0.1', ...
			'--normalcontamination', ...
			'--tumourstatestable', options.tumourStateTable, ...
			'--hgtable', options.hgtables, ...
			'--gcdir', options.gcdir, ...
			'--seqtype', 'cg', ...
			'--samplename', options.samplename, ...
			'--infile', options.infile, ...
			'--outdir', options.outdir ...
		);
toc

