clear all;
close all;
clc;

addpath('../');
addpath('../external/');

rand('state', 1);
randn('state', 1);

options.hgtables = '../config/hgTables_b37.txt'; % human genome annotation table
options.gcdir = '/data/cyau/software/gc/b37/'; % directory of local GC content files
options.outdir = '/data/cyau/ahmed/output/'; % output directory
options.tumourStateTable = '../config/tumourStatesSimple.txt';

seqerror = 0.01;
readerror = 0.01;

options.samplename = 'OP1019-illumina'; % sample name
options.infile = '/data/cyau/ahmed/OP1019/illumina/OP1019.oncoseq'; % input data file

tic;
oncoseq( 	'--read_depth_range', '[10:50]', ...
			'--chr_range', '[1]', ...
			'--n_train', '50000', ...
			'--maxploidy', '3.5', ...
			'--minploidy', '1.5', ...
			'--normalcontamination', ...
			'--maxnormalcontamination', '0.9', ...
			'--lambda1', '[ 5000 1000 500 100 50 ]', ...
			'--seqerror', num2str(seqerror), ...
			'--readerror', num2str(readerror), ...
			'--tumourstatestable', options.tumourStateTable, ...
			'--hgtable', options.hgtables, ...
			'--seqtype', 'illumina', ...
			'--samplename', options.samplename, ...
			'--infile', options.infile, ...
			'--outdir', options.outdir ...
		);
toc;


