clear all;
close all;
clc;

addpath('../');
addpath('../external/');

rand('state', 1);
randn('state', 1);

options.hgtables = '../config/hgTables_b37.txt'; % human genome annotation table
options.gcdir = '/data/cyau/software/gc/b37/'; % directory of local GC content files
options.outdir = '/data/cyau/temp/'; % output directory
options.tumourStateTable = '../config/tumourStatesCLL.txt';

options.samplename = 'multiclone.99';
options.infile = '/data/cyau/oncosnpseq/data/sim/cll/multiclone.99.oncoseq.gz'; % input data file

tic
oncoseq( 	'--read_depth_range', '[23]', ...
			'--chr_range', '[1:18]', ...
			'--lambda1', '[1000 500 250 100 50 30 10]', ...
			'--n_train', '30000', ...
			'--maxploidy', '2.5', ...
			'--minploidy', '1.5', ...
			'--seqerror', '0.001', ...
			'--readerror', '0.01', ...
			'--lambda3', '0.05', ...
			'--tumourheterogeneity', ...
			'--tumourstatestable', options.tumourStateTable, ...
			'--hgtable', options.hgtables, ...
			'--gcdir', options.gcdir, ...
			'--seqtype', 'illumina', ...
			'--samplename', options.samplename, ...
			'--infile', options.infile, ...
			'--outdir', options.outdir ...
		);
toc


