clear all;
close all;
clc;

addpath('../');
addpath('../external/');

rand('state', 1);
randn('state', 1);

options.hgtables = '../config/hgTables_b37.txt'; % human genome annotation table
options.gcdir = '/data/cyau/software/gc/b37/'; % directory of local GC content files
options.outdir = '/data/cyau/oncosnpseq/output/'; % output directory
options.tumourStateTable = '../config/tumourStates.txt';

options.samplename = 'AS_CLL_077postO';
options.infile = '/data/cyau/wgs500/pileup/snp/AS_CLL_077postO.txt.gz'; % input data file
options.normalfile = '/data/cyau/wgs500/pileup/snp/AS_CLL_077GL.txt.gz'; % input data file

options.samplename = 'AS_CLL_003-baseline';
options.infile = '/data/cyau/wgs500/pileup/snp/AS_CLL_003GL.txt.gz'; % input data file
options.normalfile = '/data/cyau/wgs500/pileup/snp/AS_CLL_003GL.txt.gz'; % input data file

tic
oncoseq( 	'--read_depth_range', '[10:40]', ...
			'--chr_range', '[ 1:23 ]', ...
			'--lambda1', '[1000 500 250 100 50 30 10]', ...
			'--n_train', '30000', ...
			'--training', ...
			'--maxploidy', '5.5', ...
			'--minploidy', '1.5', ...
			'--seqerror', '0.001', ...
			'--readerror', '0.01', ...
			'--normalcontamination', ...
			'--lambda3', '0.0', ...
			'--fast', ...
			'--tumourheterogeneity', ...
			'--tumourstatestable', options.tumourStateTable, ...
			'--hgtable', options.hgtables, ...
			'--gcdir', options.gcdir, ...
			'--seqtype', 'illumina', ...
			'--samplename', options.samplename, ...
			'--infile', options.infile, ...
			'--normalfile', options.normalfile, ...
			'--outdir', options.outdir ...
		);
toc


options.samplename = 'AS_CLL_003-lambda3';
tic
oncoseq( 	'--read_depth_range', '[10:40]', ...
			'--chr_range', '[ 1:23 ]', ...
			'--lambda1', '[1000 500 250 100 50 30 10]', ...
			'--n_train', '30000', ...
			'--training', ...
			'--maxploidy', '5.5', ...
			'--minploidy', '1.5', ...
			'--seqerror', '0.001', ...
			'--readerror', '0.01', ...
			'--normalcontamination', ...
			'--lambda3', '0.01', ...
			'--fast', ...
			'--tumourheterogeneity', ...
			'--tumourstatestable', options.tumourStateTable, ...
			'--hgtable', options.hgtables, ...
			'--gcdir', options.gcdir, ...
			'--seqtype', 'illumina', ...
			'--samplename', options.samplename, ...
			'--infile', options.infile, ...
			'--normalfile', options.normalfile, ...
			'--outdir', options.outdir ...
		);
toc




