clear all;
close all;
clc;

addpath('../');
addpath('../external/');

rand('state', 1);
randn('state', 1);

options.hgtables = '../config/hgTables_b37.txt'; % human genome annotation table
options.gcdir = '/data/cyau/software/gc/b37/'; % directory of local GC content files
options.outdir = '/data/cyau/ahmed/oncoseq/output/'; % output directory
options.tumourStateTable = '../config/tumourStatesOncoSNPSEQ.txt';

options.seqtype = 'cg'; % sequencing type 'cg' or 'illumina'

seqerror = 0.001;
readerror = 0.001;

options.samplename = 'recur'; % sample name
options.infile = '/data/cyau/ahmed/11152_recurrence/output/11152_recurrence.oncoseq'; % input data file

tic
oncoseq( 	'--read_depth_range', '[10:50]', ...
			'--chr_range', '[1:22]', ...
			'--n_train', '30000', ...
			'--maxploidy', '4.5', ...
			'--minploidy', '1.5', ...
			'--normalcontamination', ...
			'--maxnormalcontamination', '0.5', ...
			'--lambda1', '[ 1000 500 100 50 30 ]', ...
			'--seqerror', num2str(seqerror), ...
			'--readerror', num2str(readerror), ...
			'--tumourstatestable', options.tumourStateTable, ...
			'--hgtable', options.hgtables, ...
			'--gcdir', options.gcdir, ...
			'--seqtype', 'cg', ...
			'--samplename', options.samplename, ...
			'--infile', options.infile, ...
			'--outdir', options.outdir ...
		);
toc

