clear all;
close all;
clc;

addpath('../');
addpath('../external/');

rand('state', 1);
randn('state', 1);

options.hgtables = '../config/hgTables_hg38.txt'; % human genome annotation table
options.gcdir = '/data/cyau/software/gc/hg38/'; % directory of local GC content files
options.outdir = '/data/cyau/temp/'; % output directory
options.tumourStateTable = '../config/tumourStates.txt';

options.seqtype = 'illumina'; % sequencing type 'cg' or 'illumina'
options.samplename = 'AS_CLL_006R2'; % sample name
options.infile = '/data/cyau/oncosnpseq/build/out/AS_CLL_006R2.tsv'; % input data file

tic
oncoseq( 	'--read_depth_range', '[10:30]', ...
			'--chr_range', '[1:22]', ...
			'--n_train', '30000', ...
			'--maxploidy', '3.5', ...
			'--minploidy', '1.5', ...
			'--normalcontamination', ...
			'--maxnormalcontamination', '0.5', ...
			'--tumourstatestable', options.tumourStateTable, ...
			'--hgtable', options.hgtables, ...
			'--seqtype', 'illumina', ...
			'--samplename', options.samplename, ...
			'--infile', options.infile, ...
			'--outdir', options.outdir ...
		);
toc

%			'--gcdir', options.gcdir, ...

