clear all;
close all;
clc;

addpath('../');
addpath('../external/');

rand('state', 1);
randn('state', 1);

options.hgtables = '../config/hgTables_b37.txt'; % human genome annotation table
options.gcdir = '/data/cyau/software/gc/b37/'; % directory of local GC content files
options.outdir = '/data/cyau/ahmed/output/'; % output directory
options.tumourStateTable = '../config/tumourStatesCLL.txt';

seqerror = 0.01;
readerror = 0.01;

options.samplename = 'primary-all'; % sample name
options.infile = '/data/cyau/ahmed/summary/common/primary-all.consensus.oncoseq'; % input data file

tic;
oncoseq( 	'--read_depth_range', '[5:20]', ...
			'--chr_range', '[1:22]', ...
			'--n_train', '50000', ...
			'--maxploidy', '4.5', ...
			'--minploidy', '1.5', ...
			'--normalcontamination', ...
			'--maxnormalcontamination', '0.5', ...
			'--lambda1', '[ 1000 500 100 50 30 ]', ...
			'--seqerror', num2str(seqerror), ...
			'--readerror', num2str(readerror), ...
			'--tumourstatestable', options.tumourStateTable, ...
			'--hgtable', options.hgtables, ...
			'--gcdir', options.gcdir, ...
			'--seqtype', 'lfr', ...
			'--samplename', options.samplename, ...
			'--infile', options.infile, ...
			'--outdir', options.outdir ...
		);
toc;


options.samplename = [];
options.samplename{1} = 'GS000038651'; % sample name
options.samplename{2} = 'GS000038652'; % sample name
options.samplename{3} = 'GS000038653'; % sample name

for fi = 1 : 3

	options.infile = [ '/data/cyau/ahmed/summary/common/' options.samplename{fi} '.oncoseq' ]; % input data file

	tic;
	oncoseq( 	'--read_depth_range', '[10:30]', ...
				'--chr_range', '[1:22]', ...
				'--n_train', '50000', ...
				'--maxploidy', '4.5', ...
				'--minploidy', '1.5', ...
				'--normalcontamination', ...
				'--maxnormalcontamination', '0.5', ...
				'--lambda1', '[ 1000 500 100 50 30 ]', ...
				'--seqerror', num2str(seqerror), ...
				'--readerror', num2str(readerror), ...
				'--tumourstatestable', options.tumourStateTable, ...
				'--hgtable', options.hgtables, ...
				'--gcdir', options.gcdir, ...
				'--seqtype', 'cg', ...
				'--samplename', options.samplename{fi}, ...
				'--infile', options.infile, ...
				'--outdir', options.outdir ...
			);
	toc;

end








