clear all;
close all;
clc;

addpath('../');
addpath('../external/');

rand('state', 1);
randn('state', 1);

options.hgtables = '../config/hgTables_b37.txt'; % human genome annotation table
options.gcdir = '/data/cyau/software/gc/b37/'; % directory of local GC content files
options.outdir = '/data/cyau/ahmed/output/'; % output directory
options.tumourStateTable = '../config/tumourStatesCLL.txt';

options.seqtype = 'cg'; % sequencing type 'cg' or 'illumina'

seqerror = 0.01;
readerror = 0.1;

options.samplename = 'primary-all'; % sample name
options.infile = '/data/cyau/ahmed/summary/primary-all.consensus.oncoseq'; % input data file

options.samplename = 'primary-postchemo-all'; % sample name
options.infile = '/data/cyau/ahmed/summary/primary-postchemo-all.consensus.oncoseq'; % input data file


%options.samplename = 'OP1019-all'; % sample name
%options.infile = '/data/cyau/ahmed/OP1019/consensus.oncoseq'; % input data file

tic;
oncoseq( 	'--read_depth_range', '[2:15]', ...
			'--chr_range', '[1:22]', ...
			'--n_train', '50000', ...
			'--maxploidy', '4.5', ...
			'--minploidy', '1.5', ...
			'--normalcontamination', ...
			'--maxnormalcontamination', '0.5', ...
			'--lambda1', '[ 1000 500 100 50 30 ]', ...
			'--seqerror', num2str(seqerror), ...
			'--readerror', num2str(readerror), ...
			'--tumourstatestable', options.tumourStateTable, ...
			'--hgtable', options.hgtables, ...
			'--gcdir', options.gcdir, ...
			'--seqtype', 'lfr', ...
			'--samplename', options.samplename, ...
			'--infile', options.infile, ...
			'--outdir', options.outdir ...
		);
toc;

break

options.samplename = 'postchemo'; % sample name
options.infile = '/data/cyau/ahmed/oncoseq/postchemo.oncoseq'; % input data file

tic
oncoseq( 	'--read_depth_range', '[2:10]', ...
			'--chr_range', '[1:22]', ...
			'--n_train', '60000', ...
			'--maxploidy', '4.5', ...
			'--minploidy', '1.5', ...
			'--normalcontamination', ...
			'--maxnormalcontamination', '0.9', ...
			'--lambda1', '[ 1000 500 100 50 30 ]', ...
			'--seqerror', num2str(seqerror), ...
			'--readerror', num2str(readerror), ...
			'--tumourstatestable', options.tumourStateTable, ...
			'--hgtable', options.hgtables, ...
			'--gcdir', options.gcdir, ...
			'--seqtype', 'lfr', ...
			'--samplename', options.samplename, ...
			'--infile', options.infile, ...
			'--outdir', options.outdir ...
		);
toc




