clear all;
close all;
clc;

addpath('../');
addpath('../external/');

rand('state', 1);
randn('state', 1);

options.hgtables = '../config/hgTables_b37.txt'; % human genome annotation table
options.gcdir = '/data/cyau/software/gc/b37/'; % directory of local GC content files
options.outdir = '/data/cyau/downloads/skov3/out/'; % output directory
options.tumourStateTable = '../config/tumourStatesSimple.txt';

seqerror = 0.01;
readerror = 0.01;

options.samplename = 'skov3'; % sample name
options.infile = '/data/cyau/downloads/skov3/in/skov3.oncosnp'; % input data file

tic;
oncoseq( 	'--read_depth_range', '[5:20]', ...
			'--chr_range', '[1:22]', ...
			'--n_train', '30000', ...
			'--fast', ...
			'--maxploidy', '4.5', ...
			'--minploidy', '1.5', ...
			'--tumourheterogeneity', ...
			'--lambda1', '[ 1000 500 100 50 30 ]', ...
			'--seqerror', num2str(seqerror), ...
			'--readerror', num2str(readerror), ...
			'--tumourstatestable', options.tumourStateTable, ...
			'--hgtable', options.hgtables, ...
			'--gcdir', options.gcdir, ...
			'--seqtype', 'cg', ...
			'--samplename', options.samplename, ...
			'--infile', options.infile, ...
			'--outdir', options.outdir ...
		);
toc;

