clear all;
close all;
clc;

addpath('../');
addpath('../external/');

rand('state', 1);
randn('state', 1);

options.hgtables = '../config/hgTables_b37.txt'; % human genome annotation table
options.gcdir = '/data/cyau/software/gc/b37/'; % directory of local GC content files
options.outdir = '/data/cyau/temp/'; % output directory
options.tumourStateTable = '../config/tumourStates.txt';

options.samplename = 'maria';
options.infile = '/home/cyau/Dropbox/maria/input.output.forCYau/snp_SS6003119'; % input data file
options.normalfile = '/home/cyau/Dropbox/maria/input.output.forCYau/snp_SS6003118'; % input data file

tic
oncoseq( 	'--read_depth_range', '[28:32]', ...
			'--chr_range', '[ 1:23 ]', ...
			'--lambda1', '[1000 500 250 100 50 30 10]', ...
			'--n_train', '30000', ...
			'--maxploidy','5.5', ...
			'--minploidy', '1.5', ...
			'--seqerror', '0.001', ...
			'--readerror', '0.01', ...
			'--lambda3', '0.0', ...
			'--fast', ...
			'--training', ...
			'--normalcontamination', ...
			'--tumourstatestable', options.tumourStateTable, ...
			'--hgtable', options.hgtables, ...
			'--gcdir', options.gcdir, ...
			'--seqtype', 'illumina', ...
			'--samplename', options.samplename, ...
			'--infile', options.infile, ...
			'--normalfile', options.normalfile, ...
			'--outdir', options.outdir ...
		);
toc

